from typing import *


class User:

    def __init__(self, Id: int,
                 biography: str,
                 birthDate: str,
                 blockingLimit: str,
                 coverImage: str,
                 gender: str,
                 coverImageThumbnail: str,
                 followersCount: int,
                 followingsCount: int,
                 groupsUsersCount: int,
                 isAgeVerified: bool,
                 isChatRequestOn: bool,
                 isDangerous: bool,
                 isEmailConfirmed: bool,
                 isFacebookConnected: bool,
                 isFollowPending: bool,
                 isFollowedBy: bool,
                 isFollowing: bool,
                 isFromDifferentGenerationAndTrusted: bool,
                 isGroupPhoneOn: bool,
                 isHidden: bool,
                 isHideVip: bool,
                 isInterestsSelected: bool,
                 isLineConnected: bool,
                 isLobiConnected: bool,
                 isNew: bool,
                 isPhoneOn: bool,
                 isPrivate: bool,
                 isRecentlyPenalized: bool,
                 isRegistered: bool,
                 isVideoOn: bool,
                 isVip: bool,
                 maskedEmail: str,
                 mobileNumber: str,
                 nickname: str,
                 postsCount: int,
                 prefecture: str,
                 profileIcon: str,
                 profileIconThumbnail: str,
                 reviewsCount: int,
                 ):
        pass
